  // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbWOoc9G4H5c8kR7WvtTLdJ8Kd1pK3TNs',
    appId: '1:386791733630:web:18e9c60e8059515a705b2f',
    messagingSenderId: '386791733630',
    projectId: 'onechat-8d01d',
    authDomain: 'onechat-8d01d.firebaseapp.com',
    databaseURL: 'https://onechat-8d01d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'onechat-8d01d.appspot.com',
    measurementId: 'G-MP1FMFB3WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl7szAlNxG2QVWGhHuHK5KEIykznthyqU',
    appId: '1:386791733630:android:28ae2e6c05a31c8e705b2f',
    messagingSenderId: '386791733630',
    projectId: 'onechat-8d01d',
    databaseURL: 'https://onechat-8d01d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'onechat-8d01d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOR6E7H0yyc4qA0vgPMpX_k-L3mBgsyyE',
    appId: '1:386791733630:ios:9d54d40c6f003ece705b2f',
    messagingSenderId: '386791733630',
    projectId: 'onechat-8d01d',
    databaseURL: 'https://onechat-8d01d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'onechat-8d01d.appspot.com',
    iosClientId: '386791733630-519mmlh7g2cfhtdotncg9gf0rkon7vun.apps.googleusercontent.com',
    iosBundleId: 'com.example.onechatSecurity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOR6E7H0yyc4qA0vgPMpX_k-L3mBgsyyE',
    appId: '1:386791733630:ios:9d54d40c6f003ece705b2f',
    messagingSenderId: '386791733630',
    projectId: 'onechat-8d01d',
    databaseURL: 'https://onechat-8d01d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'onechat-8d01d.appspot.com',
    iosClientId: '386791733630-519mmlh7g2cfhtdotncg9gf0rkon7vun.apps.googleusercontent.com',
    iosBundleId: 'com.example.onechatSecurity',
  );
}
